### ISSUE TITLE
Portable Item Nullifier bypasses FTBU claims

### ISSUE THREAD

**Issue by OrdinatorStouff** [Bartz24/UsefulNullifiers#10]
Non-OP players are able to place blocks in "protected" FTBU claimed chunks with the Portable Item Nullifier.

Modpack: AllTheMods: Expert 1.0.30
MC: 1.10.2
Forge: 2239
usefulnullifiers-1.3.4
FTBUtilities-1.10.2-3.4.3

Also reported to FTBU: https://github.com/LatvianModder/FTBUtilities/issues/384

**Comment by Bartz24** [comment]
Chances are this is on Useful Nullifiers side, so I'll see what I can do

**Comment by LatvianModder** [comment]
Not sure what it does/how it works, but maybe you can fire on of these events when on item use?

+ PlayerInteractEvent.LeftClickBlock
+ BlockEvent.BreakEvent
+ BlockEvent.PlaceEvent (Not implemented on my side, but I will soon)
+ PlayerInteractEvent.RightClickItem
+ PlayerInteractEvent.RightClickBlock
