### ISSUE TITLE
Energy Nullifier can be filled up

### ISSUE THREAD

**Issue by sandalle** [Bartz24/UsefulNullifiers#11]
I needed a dumping ground for testing my [Draconic Evolution](https://minecraft.curseforge.com/projects/draconic-evolution) Reactor and found that the Energy Nullifiers fill up at 2.1GRF, which doesn't take long with the Reactor outputting over 500k RF/t while testing. :)

Ideally the Energy Nullifier, like the Item Nullifier, could accept an infinite amount of "stuff" and never fill up (sends to /dev/null).

**Comment by Bartz24** [comment]
Fixed for 1.3.5
