### ISSUE TITLE
Error running under 1.10.2

### ISSUE THREAD

**Issue by xenoflot** [Bartz24/UsefulNullifiers#2]
Hi,

I just installed v 1.0.2 and I get the following error: http://pastebin.com/DbzxZR1k

I'm running FTB Unstable 1.10 with a few other mods. Let me know if there's anything else I can provide to help troubleshoot.

Forge Mod Loader version 12.18.0.2000
Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_91, running on Windows 10:amd64:10.0

**Comment by Bartz24** [comment]
thanks, fixing
