### ISSUE TITLE
Server crash 1.10.2

### ISSUE THREAD

**Issue by Xobias** [Bartz24/UsefulNullifiers#3]
While connecting an item nullifier to an advanced generator item output port and also from a chest using an item conduit (ender io) from a chest to the nullifier caused a server crash where we had to remove the mod and re add it back in to be able to enter the area. Attached is the crash log.

[crash-2016-07-23_21.12.50-server.txt](https://github.com/Bartz24/UsefulNullifiers/files/379978/crash-2016-07-23_21.12.50-server.txt)

**Comment by Bartz24** [comment]
Which version of the mod are you using? Looks like the same issue from before 1.1.1

**Comment by Xobias** [comment]
It is an older version of the mod 1.0.2 will update and see if this still causes an issue. Thanks
