### ISSUE TITLE
Console spam with Hwyla

### ISSUE THREAD

**Issue by TehNut** [Bartz24/UsefulNullifiers#6]
Hwyla adds a capability handler for `IFluidHandler`. An NPE is reached [here](https://github.com/TehNut/HWYLA/blob/ac7ee51003cb7d55f8a2185c60bda87f92328b98/src/main/java/mcp/mobius/waila/addons/capability/HUDHandlerTank.java#L60) since you return `null` in `getTankProperties()` [here](https://github.com/Bartz24/UsefulNullifiers/blob/master/src/main/java/com/bartz24/usefulnullifiers/tiles/FluidVoidNullifierTile.java#L37). This method isn't nullable and should return `new IFluidTankProperties[0]` instead.

**Comment by Bartz24** [comment]
Fixed in 1.3.3
