### ISSUE TITLE
[1.11.2] Crash when opening Fluid Nullifier item

### ISSUE THREAD

**Issue by starg09** [Bartz24/UsefulNullifiers#8]
[Crash report](http://paste.feed-the-beast.com/view/030f8961)

Tested on 1.11.2 with:

* Forge 2229
* CompatLayer 0.2.2
* UN 1.3.3

**Comment by Dissgruntled** [comment]
Getting the same crash. Report is pretty much identical.

**Comment by Bartz24** [comment]
Fixed for next version
