### ISSUE TITLE
[1.10.2] The three Nullifier items have no textures on their GUIs

### ISSUE THREAD

**Issue by starg09** [Bartz24/UsefulNullifiers#9]
Tested on 1.10.2 with:

* Forge 2221
* CompatLayer 0.2.2
* UN 1.3.3

[Overflow Nullifier](http://i.imgur.com/f37IB7I.png)
[Portable Item Nullfiier](http://i.imgur.com/s2JToha.png)
[Portable Fluid Nullfiier](http://i.imgur.com/04XfYoz.png)

**Comment by Bartz24** [comment]
Fixed for next version
